"""Initial Migration

Revision ID: 5b7e70cfd5ac
Revises: 
Create Date: 2024-06-12 10:42:47.453583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b7e70cfd5ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pigs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pigs_id'), 'pigs', ['id'], unique=False)
    op.create_table('wolves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wolves_id'), 'wolves', ['id'], unique=False)
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pig_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pig_id'], ['pigs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_id'), 'houses', ['id'], unique=False)
    op.create_table('attacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wolf_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['wolf_id'], ['wolves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attacks_id'), 'attacks', ['id'], unique=False)
    # ### end Alembic commands ###

##how do undo changes 
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attacks_id'), table_name='attacks')
    op.drop_table('attacks')
    op.drop_index(op.f('ix_houses_id'), table_name='houses')
    op.drop_table('houses')
    op.drop_index(op.f('ix_wolves_id'), table_name='wolves')
    op.drop_table('wolves')
    op.drop_index(op.f('ix_pigs_id'), table_name='pigs')
    op.drop_table('pigs')
    # ### end Alembic commands ###
