"""Changed attacked foreign key

Revision ID: 7db8a5552bbf
Revises: d1d6fac4eeba
Create Date: 2024-06-12 11:07:17.021938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db8a5552bbf'
down_revision: Union[str, None] = 'd1d6fac4eeba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('attacked', sa.Boolean(), nullable=False))
    op.drop_constraint('houses_attack_id_fkey', 'houses', type_='foreignkey')
    op.drop_column('houses', 'attack_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('attack_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('houses_attack_id_fkey', 'houses', 'attacks', ['attack_id'], ['id'])
    op.drop_column('houses', 'attacked')
    # ### end Alembic commands ###
